version: '2'

services:
  go-api:
    build: ./go-api
    ports:
      - 5000:5000
    links:
      - go-api-db
    volumes:
      - ./go-api/app:/go/src/app
    command: bash -c 'cd /go/src/app/ && go run server.go'
    container_name: go-api-container

  go-api-db:
    image: postgres:10.1
    ports:
      - "5432:5432"
    volumes:
      - ./go-api-db/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin1234